spring:
  application:
    name: api-gateway

server:
  port: 8080

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ReadTimeout: 10000
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka